theme: jekyll-theme-time-machine
title: Welcome to Brendan's homepage!
description: My name is Brendan Hayes and I'm a software engineering major at RIT! I've had an interest in coding and computer science since the beginning of my time in high school
  for high school I went to Half Hallow Hills High School East. I can't wait for you guys to see my website and see you guys on campus!
  
![GitHub Logo](new-york-pizza-slice-pull.JPG)
Format: ![Alt Text](url)
